# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

# theme = "blowfish"
# baseURL = "https://your_domain.com/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
paginate = 10
summaryLength = 0

buildDrafts = false
buildFuture = false

[author]
name = "Arno / Shae"
image = "avatar.png"
links = [
    {name = "GitHub", url = "https://github.com/arnos-stuff/"},
    {name = "Twitter", url = "https://twitter.com/arnos_shae/"},
    {name = "Mail", url = "mailto://mail@arnov.dev"},
]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params.social]
  twitter = "arnos_shae"
  github = "arnos-stuff"
  email = "mail@arnov.dev"
   

[params]
author = "Arno / Shae"
description = "Arno / Shae"
copyright = "Arno / Shae with 💜"

# googleAnalytics = "G-XXXXXXXXX"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
  posts = "publications"
  authors = "authors"
  about = "about"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
